DudeAlex/AlexLeoSeleniumTests

src/test/java/OkilaTest.java
=> - added comments for TC_001.06 and TC_002.02

src/test/java/EvanMaiTest.java
TC_006.01 Evan Mai | Home Page | Featured Products: Verify number of products displayed
https://trello.com/c/zGBMoNoZ/37-tc00601-evan-mai-home-page-featured-products-verify-number-of-products-displayed
=> TC_006_01_Evan_Mai

src/test/java/ArtemTTest.java
Test_TC_001_33 to verify “Sale!” icon is present on sale products
=> Test_TC_001_33 to verify “Sale!” icon is present on sale products

src/test/java/KsutitovaTest.java
https://trello.com/c/g0Q8wOyb/79-tc011-home-page-women-page-verify-number-of-products-displayed
=> add test VerifyCardOnWomenPageeTest

src/test/java/MikeBTest.java
First Git push. All test from sprint 1.
=> Sprint1 All tests( Git first push)

src/test/java/PetroMatsiuraTest.java
=> changes in css selector length

src/test/java/AnnaMorozTest.java
added TC_002.06 [
https://trello.com/c/Q1j2pmTi/89-tc00206-annamoroz-home-page-featured-products-validate-sign-is-present-under-all-displayed-products
=> TC_002.06 AnnaMoroz 

src/test/java/NafisaTest.java
=> test 006 from Yekaterina

src/test/java/ViktoriiaKarpusTest.java
TC_005.06 Viktoriia Karpus | Home Page: Verify the Store page is opened after clicking on the "Shop Now" button
=> AddedNewTest

src/test/java/AlexFrTest.java
=> Add first test

src/test/java/AlexFrTest.java
=> Test changes

src/test/java/AlexFrTest.java
=> Refactor the second test

src/test/java/EvanMaiTest.java, src/test/java/runner/BaseTest.java
=> add BaseTest class

src/test/java/OlgaSafTest.java
изменила свой класс и добавила тест
=> My first test

src/test/java/YakuninaTest.java
=> First Selenium Test

src/test/java/YakuninaTest.java
TC_004 and TC_005 are added honoring the BaseTest class
=> TC_004 and TC_005 are added

src/test/java/KonstantinLTest.java
- renaming tests, removing code that is already existed in BaseTest class
=> Refactoring 8 tests

src/test/java/OksanaTest.java
=> Add TC_004_33

.gitignore, pom.xml, src/test/java/AlexLeoGroupJenkins06Tests.java, src/test/java/runner/BaseTest.java, src/test/java/runner/BaseUtils.java, src/test/java/runner/JenkinsUtils.java, src/test/java/runner/ProjectUtils.java, src/test/resources/local.properties.TEMPLATE
Please, carefully check and confirm!
=> new Jenkins project

src/test/java/old/EvanMaiTest.java
Create "old" package
Ignore my class and move class to the package "old"
=> Ignore tests

src/test/java/FooterTest.java
=> footer tests

src/test/java/FreestyleProjectTest.java
https://trello.com/c/tubRla1l/49-tc01102-new-item-page-create-new-freestyle-project-disable-project
=> test added testDisableProject

src/test/java/FreestyleProjectTest.java
https://trello.com/c/wJfo0kVR/94-tc01103-new-item-page-create-new-freestyle-project
=> test added testEnableProject

src/test/java/FreestyleProjectTest.java
https://trello.com/c/rG7fUgsm/95-tc01103-new-item-page-create-new-freestyle-project-add-description
=> testAddDescriptionToFreestyleProject

src/test/java/UserPageTest.java
Add new class UserPageTest
Add testVerifyUserPageMenu
TC_014 EvanMai | User page | Verify Menu Task
https://trello.com/c/eIycE2fL/102-tc014-evanmai-user-page-verify-menu-task
=> Add new test

src/test/java/old/EvanMaiTest.java, src/test/java/old/runnerOld/BaseTestOld.java
Add BaseTestOld for old project
Refactor EvanMaiTest class
Add test
=> Refactoring Old

src/test/java/old/EvanMaiTest.java
=> remove jdk.jfr.Description
